Dev
nhhaidee/wgscovplot pull request #1
Opened 2021-08-05 13:24 UTC by nhhaidee

The objectives of the first PR of project

1. Create structure for project
2. First basic coverage plot

2021-08-10 14:50 UTC, peterk87 requested changes
Hi Hai,

Thanks for getting the initial skeleton for this project together. In addition to addressing the minor comments I made, there's some things that I'd like you to look into:

- Compression of depth integer values. Base64 binary representation of an array of ints (e.g. [Uint16Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array))
- Removing the x-axis list of integer values; generating it on the fly given a range. Is there an ECharts range func you can use instead?
- How will multiple samples be handled? Is it possible to render multiple plots stacked on top of each other sharing the same x- and y-axes limits?
- Should the `render.html` be included in the repo? It's a lot of extra data to include in the repo.
- Event listeners for window resizing, changing the theme, panning/zooming/tooltips/brush selection.

---

Some general code comments:

- Please try to use pure functions whenever possible for easy testing and reasoning about the code.
- Ultimately, this code just seems to be writing some JSON using a dict of data. Using so many classes and with multiple levels of inheritance obscures this and makes it seem like there's something much more complicated going on than is actually going on. It's much easier to manipulate dicts/sets/lists than objects as there are many general functions that work on these basic data structures. Please try to use basic data structures and functions (functional style) before resorting to using classes (object oriented); it makes the code easier to understand and test.

2021-08-10 14:50 UTC, peterk87 commented on sequencing_coverage_plot/ultilities/utils.py
> +def replace_placeholder(html: str) -> str:
Why is this function necessary if Jinja2 is used for templating?

2021-08-10 14:50 UTC, peterk87 commented on sequencing_coverage_plot/render/engine.py
> +class RenderEngine:
This class doesn't seem to add much and just seems to obfuscate what is being done.

The functionality in this class could be moved to the `render_html` function and it would be more clear what is going on.

2021-08-10 14:50 UTC, peterk87 commented on sequencing_coverage_plot/coverage_plot/base_plot.py
> +class BasicOpts:
I think it would be much more clear to just use dicts instead of classes that act like dicts for storing options. They're more flexible and easy to change and understand.

Python 3.9 also adds new dictionary merge/update operators (https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators) so handling options should be easier.

2021-08-10 14:50 UTC, peterk87 commented on .gitignore
> +test.py
The `test.py` is supposed to be ignored, but it's included in the repo. If it's not supposed to be part of the repo, please remove it.

2021-08-10 19:50 UTC, nhhaidee commented on sequencing_coverage_plot/coverage_plot/base_plot.py
> +        logging.basicConfig(
I temporarily placed logging in ```__init__``` function of  BasePlot class, when this class is initialised, then we can use logging for debugging or info

Later on, if we decide this is a CLI app, I will move to main entry

2021-08-10 19:52 UTC, nhhaidee commented on sequencing_coverage_plot/globals_parameters.py
> +class _RenderType:
Updated by using Eum class https://github.com/nhhaidee/sequencing_coverage_plot/commit/89c11f3d4221419caa553dc959fe8fe586c1cfb2

2021-08-10 19:58 UTC, nhhaidee commented on sequencing_coverage_plot/render/engine.py
> +class RenderEngine:
Removed class and replaced by pure function https://github.com/nhhaidee/sequencing_coverage_plot/commit/89c11f3d4221419caa553dc959fe8fe586c1cfb2

2021-08-10 19:59 UTC, nhhaidee commented on .gitignore
> +test.py
Removed it

2021-08-10 20:02 UTC, nhhaidee commented on sequencing_coverage_plot/coverage_plot/base_plot.py
> +class BasicOpts:
I created ```options_dict.py``` to store all options for echarts, so we can use update/merge operators

2021-08-10 20:04 UTC, nhhaidee commented on test.py
> +cov_file1 = '/home/hnguyen/Documents/LabData/results/mapping/sample-01.fastq/sample-01.fastq-MN908947.3-depths.tsv'
I removed test.py and will use pytest for unit and functional test

2021-08-10 20:22 UTC, nhhaidee commented on sequencing_coverage_plot/ultilities/utils.py
> +def replace_placeholder(html: str) -> str:
Removed it as it is unnecessary https://github.com/nhhaidee/sequencing_coverage_plot/commit/3d5091e905d4ddfcc092aa4d891673d4c96a6ca9

2021-08-10 20:26 UTC, nhhaidee commented on test.py
> +from sequencing_coverage_plot import CoveragePlot
Will use pytest for unit and functional test for project in next PRs

2021-08-10 20:34 UTC, nhhaidee commented
Hi Peter,

The below features are must-have feature for this tool and I am working on that:

1. Handling multiple samples
2. A drop-down list to select coverage plot for each samples
3. The multiple plots stacked, gird display
4. Zoom in/out, tooltip, change color/themes
5. Log scale for coverage

Thanks,
Hai

2021-09-17 19:16 UTC, nhhaidee commented
Addressed below requirements for this first PR, so merge and close PR
1. Created structure for project
2. Tool generated coverage plot for SARS-COV2

2021-09-17 19:20 UTC, merged